# ////////////////| [âš™ï¸] | Settings | [ğŸ› ï¸] |//////////////// #
# if you need help just contact me though Discord TheH2SO4#0284

# | BeaterMiner settings
donate: '5' # What you want to donate. Ej: 5 (Set to 0 if you don't want to donate)